### ISSUE TITLE
Image not generated

### ISSUE THREAD

**Issue by outline4** [jmoont/pdfthumb#1]
Hi, 
I would love to use your plugin but the image is not output. 

I've specified the following folders: 
Storage Path: /home/outline4/www/xxxxxx/public_html/documents/pdfThumbs/ (DOCUMENT_ROOT)
Base URL:  /documents/pdfThumbs/

It created the folder "previews" within the pdfThumbs template.  
And it creates an image url: 
/documents/pdfThumbs/previews/c26c3242ef8985259ac2b28d10481341.jpg

But the image itself is not created.  
I guess it's the "Storage Path" that is not correct? 

I've tried all sorts of "Storage paths", but none of them seem to work.  
Could you point me into the right direction? 

Cheers
Stefan

Btw: If I specify Base URL:  @web/documents/pdfThumbs/ The @web part is not translated to the url.

**Comment by jmoont** [comment]
Thanks for taking a look at my plugin.

Try setting the Storage Path to:
`@webroot/documents/pdfThumbs`

and the Base URL to:
`/documents/pdfThumbs/`

Unfortunately, I haven't implemented @web support yet.
Let me know if this works for you.

**Comment by outline4** [comment]
That's what I first tried... 
With no trailing slash at the storage path and a trailing slash at the base Url. 

I also limited the upload directory to only one folder... and the type of file to only pdf. 

Still - no image created. 

hm? anything else I could try?

**Comment by jmoont** [comment]
Are there any errors in the logs?

**Comment by outline4** [comment]
No I did not spot any errors… I’ve followed an issue on the v2 branch… but did not see any errors...

**Comment by jmoont** [comment]
Have you tried running it locally? Could it be a permissions issue?

**Comment by jmoont** [comment]
Did you have any luck in getting it to work?

**Comment by jmoont** [comment]
I'm closing this for now - please let me know if you had further issues.

**Comment by G17creative** [comment]
Hi there, we're experiencing the same issue. The preview folder is being created but no images are being generated

**Comment by bymayo** [comment]
Same issue. But I have a feeling this has something to do with it trying to locate the file in a subdirectory?

**Comment by mark-chief** [comment]
I am having this issue also...

**Comment by scuocere** [comment]
Hello, thanks for writing the nice plugin. Unfortunately i have the same problem. I have a multisite and multilanguage environment, if this has something to do with. My error message in the frontend is:
Trying to get property 'size' of non-object

**Comment by bymayo** [comment]
@scuocere @mark-chief @G17creative @outline4 

I'm unsure if this plugin is being maintained anymore, so I had to go ahead and create my own plugin (Using a different PDF to Image library)

https://github.com/bymayo/craft-pdf-transform
