### ISSUE TITLE
Thumbnails do not get generated

### ISSUE THREAD

**Issue by nicbou** [jmoont/pdfthumb#4]
I have an issue with this plugin that I simply cannot fix. The thumbnails for my documents do not get generated. The /previews/ directory gets generated, but it's completely empty, and the thumbnail URLs 404.

Since the /previews/ directory is created, I assume it's not a permissions issue. The logs are empty.

I will try to debug it myself, but I'm a bit stumped because the older plugin worked fine with Craft 2 in the same environment.

**Comment by nicbou** [comment]
I dug a bit deeper. It looks like imagemagick silently fails. I reintroduced logging and found that it indeed crashed with some PDFs. I will close this issue as the problem is not with PDFThumb.

Thanks for your hard work. This plugin is really useful.

**Comment by meredevelopment** [comment]
@nicbou I'm facing the same issue, but so far I've not been able to find a fix. Can I please ask how you enabled IM logging? Thanks!

**Comment by nicbou** [comment]
I hard-coded it. In the end, updating ImageMagick fixed it. It required updating many other things, but it worked.
